### PR TITLE
update setup_otc.sh

### PR DESCRIPTION
**Pull request by edarzi**
Support CloudManager new authentication method with Auth0
Cloud manager is not using local authentication anymore and there is must to work with Auth0

new prerequisites for using it is to have user register in https://cloud.netapp.com

### CODE REVIEW

**Comment by bmoller** [comment]
I've tested the updated script and it launches successfully. However, we'll need a documentation update in concert with this change to point out Eran's statement: users must first register at cloud.netapp.com and then provide those credentials as values for the QS parameters.

**Comment by sshvans** [comment]
Thanks @edarzi for the PR and @bmoller for testing the changes! We need to add the parameters to the template as well to pass the auth token before we can merge this PR.

**Comment by edarzi** [comment]
In case we want to change script and to pass token instead of password, need to perform the following in order to get the token:

Authentication Information
NetApp Cloud Central uses OAuth 2.0, an industry-standard protocol, for authorization. Communicating with one of the NetApp Cloud Central authenticated endpoints requires acquiring a JWT access token from the OAuth token endpoint.
For purposes of using the execution feature of this API documentation, you may login using the UI login screen. This will automatically assign the relevant access token. If you wish, you can follow the instructions below and generate an access token via the API, then paste the JWT token in the corresponding box.
How to Acquire a JWT Access Token

  *   Make an HTTP POST request to the endpoint
https://netapp-cloud-account.auth0.com/oauth/token

  *   Include the header
Content-Type: application/json

  *   Body for regular user login (not LDAP)
·         COPY TO CL{
·             "grant_type": "password",
·             "username": "YOUR_EMAIL_ADDRESS",
·             "password": "YOUR_PASSWORD",
·             "audience": "https://cloudmanager.cloud.netapp.com",
·             "client_id": "QC3AgHk6qdbmC7Yyr82ApBwaaJLwRrNO"
}
IPBOARD

  *   Acquiring a token for federated login is handled in a different manner. For more information, please contact us.
The response of the API call to get an access token includes the field 'accessToken'. After acquiring the access token, include the following header in all calls to an authenticated endpoint.
Authorization: Bearer YOUR_TOKEN


Let me know if you want me to test and update the script that will get token instead of password

Thanks,
Eran

**Comment by bmoller** [comment]
@sshvans I think there's a bit of misunderstanding here. What Eran meant, and I tested this, is that instead of the user entering a new password and user as part of launching the template, they must first register with NetApp's site. Once that's done, they provide the same credentials for the template's parameters. We don't need to add any new parameters, but should probably update the descriptions to reflect where they come from.

**Comment by edarzi** [comment]
Hi Shivansh

Can you update regarding the merge of that pull request?

Thanks,
Eran

**Comment by sshvans** [comment]
@edarzi Since this PR requires user to register on netapp website first to get the credentials, we need to update that in the deployment guide. Let me send you the guide via email to update. 
Also, this PR needs to be submitted against develop branch. Can you make that change and resolve any conflicts?

**Pull request merged**
